//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /SSD1/Repositories/C#/Heretical Engine/Heretical Engine Core/Engine/Grammars/GLSL/GLSLParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace HereticalSolutions.HereticalEngine.Grammars {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GLSLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGLSLParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] GLSLParser.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_identifier([NotNull] GLSLParser.Variable_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] GLSLParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_expression([NotNull] GLSLParser.Postfix_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.field_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_selection([NotNull] GLSLParser.Field_selectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.integer_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger_expression([NotNull] GLSLParser.Integer_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] GLSLParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_identifier([NotNull] GLSLParser.Function_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_call_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_parameters([NotNull] GLSLParser.Function_call_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] GLSLParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] GLSLParser.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_expression([NotNull] GLSLParser.Assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] GLSLParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_expression([NotNull] GLSLParser.Binary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GLSLParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] GLSLParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] GLSLParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] GLSLParser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_prototype([NotNull] GLSLParser.Function_prototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameters([NotNull] GLSLParser.Function_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.parameter_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declarator([NotNull] GLSLParser.Parameter_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declaration([NotNull] GLSLParser.Parameter_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.parameter_type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_type_specifier([NotNull] GLSLParser.Parameter_type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit_declarator_list([NotNull] GLSLParser.Init_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.single_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_declaration([NotNull] GLSLParser.Single_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.typeless_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeless_declaration([NotNull] GLSLParser.Typeless_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.fully_specified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFully_specified_type([NotNull] GLSLParser.Fully_specified_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.invariant_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvariant_qualifier([NotNull] GLSLParser.Invariant_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.interpolation_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolation_qualifier([NotNull] GLSLParser.Interpolation_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.layout_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier([NotNull] GLSLParser.Layout_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.layout_qualifier_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id_list([NotNull] GLSLParser.Layout_qualifier_id_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.layout_qualifier_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id([NotNull] GLSLParser.Layout_qualifier_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.precise_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecise_qualifier([NotNull] GLSLParser.Precise_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_qualifier([NotNull] GLSLParser.Type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.single_type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_type_qualifier([NotNull] GLSLParser.Single_type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.storage_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_qualifier([NotNull] GLSLParser.Storage_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.type_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name_list([NotNull] GLSLParser.Type_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] GLSLParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier([NotNull] GLSLParser.Type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_specifier([NotNull] GLSLParser.Array_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension([NotNull] GLSLParser.DimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.type_specifier_nonarray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier_nonarray([NotNull] GLSLParser.Type_specifier_nonarrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.precision_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecision_qualifier([NotNull] GLSLParser.Precision_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.struct_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_specifier([NotNull] GLSLParser.Struct_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.struct_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration_list([NotNull] GLSLParser.Struct_declaration_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration([NotNull] GLSLParser.Struct_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator_list([NotNull] GLSLParser.Struct_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator([NotNull] GLSLParser.Struct_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] GLSLParser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_list([NotNull] GLSLParser.Initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.declaration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_statement([NotNull] GLSLParser.Declaration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GLSLParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.simple_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_statement([NotNull] GLSLParser.Simple_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement([NotNull] GLSLParser.Compound_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_no_new_scope([NotNull] GLSLParser.Statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.compound_statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement_no_new_scope([NotNull] GLSLParser.Compound_statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] GLSLParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] GLSLParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_statement([NotNull] GLSLParser.Selection_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.selection_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_rest_statement([NotNull] GLSLParser.Selection_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] GLSLParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] GLSLParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_label([NotNull] GLSLParser.Case_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_statement([NotNull] GLSLParser.Iteration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.for_init_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_init_statement([NotNull] GLSLParser.For_init_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.for_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_rest_statement([NotNull] GLSLParser.For_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_statement([NotNull] GLSLParser.Jump_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_declaration([NotNull] GLSLParser.External_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] GLSLParser.Function_definitionContext context);
}
} // namespace HereticalSolutions.HereticalEngine.Grammars
