//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /SSD1/Repositories/C#/Heretical Engine/Heretical Engine Core/Engine/Grammars/GLSL/GLSLPreParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace HereticalSolutions.HereticalEngine.Grammars {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GLSLPreParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGLSLPreParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] GLSLPreParser.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.compiler_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompiler_directive([NotNull] GLSLPreParser.Compiler_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.behavior"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBehavior([NotNull] GLSLPreParser.BehaviorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] GLSLPreParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.define_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefine_directive([NotNull] GLSLPreParser.Define_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.elif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElif_directive([NotNull] GLSLPreParser.Elif_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.else_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_directive([NotNull] GLSLPreParser.Else_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.endif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndif_directive([NotNull] GLSLPreParser.Endif_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.error_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_directive([NotNull] GLSLPreParser.Error_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_message([NotNull] GLSLPreParser.Error_messageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.extension_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_directive([NotNull] GLSLPreParser.Extension_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.extension_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_name([NotNull] GLSLPreParser.Extension_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.group_of_lines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_of_lines([NotNull] GLSLPreParser.Group_of_linesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.if_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_directive([NotNull] GLSLPreParser.If_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.ifdef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfdef_directive([NotNull] GLSLPreParser.Ifdef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.ifndef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfndef_directive([NotNull] GLSLPreParser.Ifndef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.line_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_directive([NotNull] GLSLPreParser.Line_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.line_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_expression([NotNull] GLSLPreParser.Line_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.macro_esc_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_esc_newline([NotNull] GLSLPreParser.Macro_esc_newlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.macro_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_identifier([NotNull] GLSLPreParser.Macro_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.macro_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_name([NotNull] GLSLPreParser.Macro_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.macro_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_text([NotNull] GLSLPreParser.Macro_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.macro_text_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_text_([NotNull] GLSLPreParser.Macro_text_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] GLSLPreParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOff([NotNull] GLSLPreParser.OffContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.on"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn([NotNull] GLSLPreParser.OnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.pragma_debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_debug([NotNull] GLSLPreParser.Pragma_debugContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.pragma_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_directive([NotNull] GLSLPreParser.Pragma_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.pragma_optimize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_optimize([NotNull] GLSLPreParser.Pragma_optimizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProfile([NotNull] GLSLPreParser.ProfileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.program_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram_text([NotNull] GLSLPreParser.Program_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.stdgl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStdgl([NotNull] GLSLPreParser.StdglContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.undef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUndef_directive([NotNull] GLSLPreParser.Undef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLPreParser.version_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion_directive([NotNull] GLSLPreParser.Version_directiveContext context);
}
} // namespace HereticalSolutions.HereticalEngine.Grammars
